### ISSUE TITLE
Not able to build container docker build -t azure-sphere .

### ISSUE THREAD

**Issue by jeevannagvekar** [edgeimpulse/example-azure-sphere-mt3620#2]
Hello, 
While trying to build container, I am getting below error. 
Azure Sphere Installation getting cancelled. Note that I already have Azure Sphere SDK installed on my laptop.

Environment: 
Machine: Laptop
OS: Windows10
Docker: v20.10.5
Ran the command from cmd prompt (admin privilege) and powershell (admin privilege). 
_____________________________________________________________________________________________________________________________
------
 > [5/7] RUN /bin/bash ./install_azure_sphere_sdk.sh:
#9 1.517 logname: no login name
#9 1.566 Downloading Azure Sphere SDK tarball from 'https://aka.ms/AzureSphereSDKDownload/Linux'...
#9 1.570 Installing Azure Sphere SDK version 21.2.1.28749.
#9 80.95 Validating signature.
#9 81.69 Installing SDK files.
#9 84.60 chmod: cannot access '/opt/azurespheresdk/Tools/azsphere_connect.sh': No such file or directory
#9 96.96 ERROR: Could not mark file /opt/azurespheresdk/Tools/azsphere_connect.sh as executable. Please try again or visit https://aka.ms/AzureSphereSDK/Linux for more information.
#9 96.97 Cancelled during installation, rolling back to clean state.
#9 96.98 Removing installed files.
#9 96.98 Removing Azure Sphere CLI from PATH, if present.
#9 96.99 Removing default udev configuration, if present.
#9 97.00 Azure Sphere SDK installation cancelled.
#9 97.00
------
executor failed running [/bin/sh -c /bin/bash ./install_azure_sphere_sdk.sh]: exit code: 1

D:\AzureSphere\EdgeImpulse\example-azure-sphere-mt3620>

_____________________________________________________________________________________________________________________________

**Comment by janjongboom** [comment]
Hi @jeevannagvekar sorry I never saw this ticket. Even though I'm using an install script for a specific version it just downloads the latest SDK instead, which is a moving target, so no way to write a build script that just works. I've reached out to Microsoft to see if there's a way to properly pin this!

**Comment by janjongboom** [comment]
Hi, updated the install script now!
